CREATE TABLE knowledge_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    claim TEXT,
    content TEXT NOT NULL,
    summary TEXT,
    knowledge_type VARCHAR(64),
    trust_level VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    user_id VARCHAR(64),
    conversation_id VARCHAR(64),
    project_id VARCHAR(64),
    tenant_id VARCHAR(64),
    source_type VARCHAR(64),
    source_ref TEXT,
    evidence TEXT,
    embedding_id VARCHAR(128),
    embedding_model VARCHAR(128),
    embedding_dimension INT,
    confidence NUMERIC(5,4),
    privacy_score NUMERIC(5,4),
    version INT NOT NULL DEFAULT 1,
    hash VARCHAR(64) NOT NULL UNIQUE,
    approved_by VARCHAR(64),
    approved_at TIMESTAMP WITH TIME ZONE,
    reject_reason TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_knowledge_retrieval
    ON knowledge_item(status, trust_level, scope_type);
CREATE INDEX idx_knowledge_scope_owner
    ON knowledge_item(tenant_id, project_id, user_id, conversation_id);

CREATE TABLE rag_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64),
    conversation_id VARCHAR(64),
    project_id VARCHAR(64),
    tenant_id VARCHAR(64),
    question TEXT NOT NULL,
    rewritten_query TEXT,
    final_prompt TEXT,
    answer TEXT,
    max_vector_score NUMERIC(8,6),
    avg_vector_score NUMERIC(8,6),
    max_rerank_score NUMERIC(8,6),
    answer_confidence NUMERIC(5,4),
    possible_gap BOOLEAN NOT NULL DEFAULT FALSE,
    gap_score NUMERIC(5,4),
    gap_types TEXT,
    gap_reason TEXT,
    prompt_tokens INT,
    completion_tokens INT,
    latency_ms BIGINT,
    status VARCHAR(32),
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE retrieval_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    knowledge_id BIGINT,
    query TEXT,
    search_type VARCHAR(32),
    vector_score NUMERIC(8,6),
    keyword_score NUMERIC(8,6),
    rerank_score NUMERIC(8,6),
    trust_score NUMERIC(8,6),
    final_score NUMERIC(8,6),
    trust_level VARCHAR(32),
    scope_type VARCHAR(32),
    rank_no INT,
    used_in_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_retrieval_trace FOREIGN KEY (trace_id) REFERENCES rag_trace(trace_id)
);

CREATE INDEX idx_retrieval_trace ON retrieval_log(trace_id, rank_no);

CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64),
    feedback_type VARCHAR(64) NOT NULL,
    feedback_content TEXT,
    corrected_answer TEXT,
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_feedback_trace FOREIGN KEY (trace_id) REFERENCES rag_trace(trace_id)
);

CREATE TABLE review_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    reviewer_id VARCHAR(64),
    review_action VARCHAR(64),
    review_comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_review_knowledge FOREIGN KEY (knowledge_id) REFERENCES knowledge_item(id)
);

CREATE INDEX idx_review_pending ON review_task(status, created_at);
