ALTER TABLE retrieval_log ADD COLUMN vector_rank INT;
ALTER TABLE retrieval_log ADD COLUMN keyword_rank INT;
ALTER TABLE retrieval_log ADD COLUMN rrf_score NUMERIC(8,6);

CREATE TABLE index_sync_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_id BIGINT NOT NULL,
    target_index VARCHAR(32) NOT NULL,
    operation VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    target_status VARCHAR(32),
    retry_count INT NOT NULL DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    finished_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_index_sync_knowledge
        FOREIGN KEY (knowledge_id) REFERENCES knowledge_item(id)
);

CREATE INDEX idx_index_sync_runnable
    ON index_sync_task(status, retry_count, created_at);
CREATE INDEX idx_index_sync_knowledge
    ON index_sync_task(knowledge_id, target_index, status);
