package io.github.trustrag.core.model;

public enum KnowledgeGapType {
    NO_RETRIEVAL,
    LOW_RETRIEVAL_SCORE,
    LOW_RERANK_SCORE,
    INSUFFICIENT_CONTEXT,
    ONLY_LOW_TRUST_MATCHED,
    ANSWER_UNCERTAIN,
    USER_CORRECTION,
    NEGATIVE_FEEDBACK,
    TOOL_RESULT_MISSING,
    CONFLICT_FOUND,
    KNOWLEDGE_OUTDATED
}
