CREATE TABLE knowledge_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255), claim CLOB, content CLOB NOT NULL, summary CLOB, knowledge_type VARCHAR(64),
    trust_level VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, scope_type VARCHAR(32) NOT NULL,
    user_id VARCHAR(64), conversation_id VARCHAR(64), project_id VARCHAR(64), tenant_id VARCHAR(64),
    source_type VARCHAR(64), source_ref CLOB, evidence CLOB, embedding_id VARCHAR(128),
    embedding_model VARCHAR(128), embedding_dimension INT, confidence DECIMAL(5,4),
    privacy_score DECIMAL(5,4), version INT NOT NULL DEFAULT 1, hash VARCHAR(64) NOT NULL UNIQUE,
    approved_by VARCHAR(64), approved_at TIMESTAMP, reject_reason CLOB,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, expires_at TIMESTAMP
);
CREATE TABLE rag_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64), conversation_id VARCHAR(64), project_id VARCHAR(64), tenant_id VARCHAR(64),
    question CLOB NOT NULL, rewritten_query CLOB, final_prompt CLOB, answer CLOB,
    max_vector_score DECIMAL(8,6), avg_vector_score DECIMAL(8,6), max_rerank_score DECIMAL(8,6),
    answer_confidence DECIMAL(5,4), possible_gap BOOLEAN NOT NULL, gap_score DECIMAL(5,4),
    gap_types CLOB, gap_reason CLOB, prompt_tokens INT, completion_tokens INT, latency_ms BIGINT,
    status VARCHAR(32), error_message CLOB, created_at TIMESTAMP NOT NULL
);
CREATE TABLE retrieval_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL,
    knowledge_id BIGINT, query CLOB, search_type VARCHAR(32), vector_score DECIMAL(8,6),
    keyword_score DECIMAL(8,6), rerank_score DECIMAL(8,6), trust_score DECIMAL(8,6),
    final_score DECIMAL(8,6), trust_level VARCHAR(32), scope_type VARCHAR(32), rank_no INT,
    used_in_prompt BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64), feedback_type VARCHAR(64) NOT NULL, feedback_content CLOB,
    corrected_answer CLOB, processed BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE review_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL, reviewer_id VARCHAR(64), review_action VARCHAR(64),
    review_comment CLOB, created_at TIMESTAMP NOT NULL, reviewed_at TIMESTAMP
);
