CREATE TABLE knowledge_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255), claim CLOB, content CLOB NOT NULL, summary CLOB, knowledge_type VARCHAR(64),
    trust_level VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, scope_type VARCHAR(32) NOT NULL,
    user_id VARCHAR(64), conversation_id VARCHAR(64), project_id VARCHAR(64), tenant_id VARCHAR(64),
    source_type VARCHAR(64), source_ref CLOB, evidence CLOB, embedding_id VARCHAR(128),
    embedding_model VARCHAR(128), embedding_dimension INT, confidence DECIMAL(5,4),
    privacy_score DECIMAL(5,4), version INT NOT NULL DEFAULT 1, hash VARCHAR(64) NOT NULL UNIQUE,
    approved_by VARCHAR(64), approved_at TIMESTAMP, reject_reason CLOB,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, expires_at TIMESTAMP,
    promotion_stage VARCHAR(64), promotion_score DECIMAL(5,4), llm_pre_review_result CLOB,
    normalized_claim CLOB, claim_hash VARCHAR(64), llm_score DECIMAL(5,4),
    source_score DECIMAL(5,4), evidence_score DECIMAL(5,4), feedback_score DECIMAL(5,4),
    usage_score DECIMAL(5,4), general_value_score DECIMAL(5,4),
    privacy_risk DECIMAL(5,4) DEFAULT 0, conflict_risk DECIMAL(5,4) DEFAULT 0,
    stale_risk DECIMAL(5,4) DEFAULT 0, applicable_version VARCHAR(128),
    valid_from TIMESTAMP, valid_to TIMESTAMP, source_time TIMESTAMP, last_verified_at TIMESTAMP,
    usage_count INT DEFAULT 0, positive_feedback_count INT DEFAULT 0,
    negative_feedback_count INT DEFAULT 0, tags_json CLOB,
    previous_trust_level VARCHAR(32), previous_status VARCHAR(32),
    source_title VARCHAR(512), source_url CLOB, page_number INT,
    section_path CLOB, document_id VARCHAR(64), chunk_index INT
);
CREATE TABLE rag_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64), conversation_id VARCHAR(64), project_id VARCHAR(64), tenant_id VARCHAR(64),
    question CLOB NOT NULL, rewritten_query CLOB, final_prompt CLOB, answer CLOB,
    max_vector_score DECIMAL(16,6), avg_vector_score DECIMAL(16,6), max_rerank_score DECIMAL(16,6),
    answer_confidence DECIMAL(5,4), possible_gap BOOLEAN NOT NULL, gap_score DECIMAL(5,4),
    gap_types CLOB, gap_reason CLOB, prompt_tokens INT, completion_tokens INT, latency_ms BIGINT,
    status VARCHAR(32), error_message CLOB, created_at TIMESTAMP NOT NULL,
    trace_type VARCHAR(32) NOT NULL DEFAULT 'NORMAL', eval_run_id BIGINT, eval_case_id BIGINT
);
CREATE TABLE retrieval_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL,
    knowledge_id BIGINT, query CLOB, search_type VARCHAR(32), vector_score DECIMAL(16,6),
    keyword_score DECIMAL(16,6), vector_rank INT, keyword_rank INT, rrf_score DECIMAL(8,6),
    rerank_score DECIMAL(16,6), trust_score DECIMAL(8,6),
    final_score DECIMAL(8,6), trust_level VARCHAR(32), scope_type VARCHAR(32), rank_no INT,
    used_in_prompt BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64), feedback_type VARCHAR(64) NOT NULL, feedback_content CLOB,
    corrected_answer CLOB, processed BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE review_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL, reviewer_id VARCHAR(64), review_action VARCHAR(64),
    review_comment CLOB, created_at TIMESTAMP NOT NULL, reviewed_at TIMESTAMP
);
CREATE TABLE promotion_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL, task_type VARCHAR(32) NOT NULL, retry_count INT DEFAULT 0,
    error_message CLOB, started_at TIMESTAMP, finished_at TIMESTAMP, created_at TIMESTAMP NOT NULL
);
CREATE TABLE index_sync_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_id BIGINT NOT NULL,
    target_index VARCHAR(32) NOT NULL, operation VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL, target_status VARCHAR(32), retry_count INT DEFAULT 0,
    error_message CLOB, created_at TIMESTAMP NOT NULL, started_at TIMESTAMP,
    finished_at TIMESTAMP
);
CREATE TABLE conflict_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_knowledge_id BIGINT NOT NULL,
    existing_knowledge_id BIGINT NOT NULL, conflict_type VARCHAR(32) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL, reason CLOB, created_at TIMESTAMP NOT NULL
);
CREATE TABLE knowledge_lineage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_id BIGINT NOT NULL,
    parent_knowledge_id BIGINT, source_trace_id VARCHAR(64), source_feedback_id BIGINT,
    action VARCHAR(128) NOT NULL, operator_type VARCHAR(32) NOT NULL,
    operator_id VARCHAR(64), created_at TIMESTAMP NOT NULL
);
CREATE TABLE document_import_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(64) NOT NULL UNIQUE, source_kind VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL, original_filename VARCHAR(512),
    content_type VARCHAR(255), source_uri CLOB, storage_path CLOB,
    git_ref VARCHAR(255), title VARCHAR(512), source_type VARCHAR(64) NOT NULL,
    trust_level VARCHAR(32) NOT NULL, scope_type VARCHAR(32) NOT NULL,
    user_id VARCHAR(64), conversation_id VARCHAR(64), project_id VARCHAR(64),
    tenant_id VARCHAR(64), total_documents INT DEFAULT 0, total_sections INT DEFAULT 0,
    imported_count INT DEFAULT 0, duplicate_count INT DEFAULT 0, failed_count INT DEFAULT 0,
    retry_count INT DEFAULT 0, error_message CLOB, created_at TIMESTAMP NOT NULL,
    started_at TIMESTAMP, finished_at TIMESTAMP, updated_at TIMESTAMP NOT NULL
);

CREATE TABLE eval_dataset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL, description CLOB, tenant_id VARCHAR(64), project_id VARCHAR(64),
    created_by VARCHAR(64), enabled BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
CREATE TABLE eval_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL, question CLOB NOT NULL, expected_answer CLOB,
    tenant_id VARCHAR(64), project_id VARCHAR(64), user_id VARCHAR(64),
    conversation_id VARCHAR(64), tags CLOB, difficulty VARCHAR(32),
    enabled BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL
);
CREATE TABLE eval_case_expected_knowledge (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eval_case_id BIGINT NOT NULL, knowledge_id BIGINT NOT NULL,
    relevance_grade INT NOT NULL, created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_eval_expected_case FOREIGN KEY (eval_case_id) REFERENCES eval_case(id),
    CONSTRAINT fk_eval_expected_knowledge FOREIGN KEY (knowledge_id) REFERENCES knowledge_item(id)
);
CREATE TABLE eval_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT NOT NULL, run_name VARCHAR(255), run_type VARCHAR(32) NOT NULL,
    before_after_group VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL,
    total_count INT DEFAULT 0, success_count INT DEFAULT 0, failed_count INT DEFAULT 0,
    engine_config_snapshot CLOB, model_config_snapshot CLOB,
    knowledge_snapshot_time TIMESTAMP, started_at TIMESTAMP, finished_at TIMESTAMP,
    error_message CLOB, created_by VARCHAR(64), created_at TIMESTAMP NOT NULL
);
CREATE TABLE eval_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eval_run_id BIGINT NOT NULL, eval_case_id BIGINT NOT NULL, trace_id VARCHAR(64),
    question CLOB NOT NULL, expected_answer CLOB, answer CLOB,
    retrieved_count INT DEFAULT 0, expected_knowledge_count INT DEFAULT 0,
    recall_at_5 DECIMAL(8,6), recall_at_10 DECIMAL(8,6),
    precision_at_5 DECIMAL(8,6), precision_at_10 DECIMAL(8,6),
    mrr DECIMAL(8,6), ndcg_at_5 DECIMAL(8,6), ndcg_at_10 DECIMAL(8,6),
    faithfulness DECIMAL(8,6), answer_correctness DECIMAL(8,6),
    answer_relevance DECIMAL(8,6), hallucination_score DECIMAL(8,6),
    prompt_tokens INT DEFAULT 0, completion_tokens INT DEFAULT 0, latency_ms BIGINT DEFAULT 0,
    status VARCHAR(32) NOT NULL, error_message CLOB, created_at TIMESTAMP NOT NULL
);
CREATE TABLE eval_judge_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eval_result_id BIGINT NOT NULL, eval_run_id BIGINT NOT NULL, eval_case_id BIGINT NOT NULL,
    judge_type VARCHAR(64) NOT NULL, model VARCHAR(128), prompt CLOB, raw_output CLOB,
    score DECIMAL(8,6), passed BOOLEAN, reason CLOB, created_at TIMESTAMP NOT NULL
);
CREATE TABLE eval_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    eval_run_id BIGINT NOT NULL UNIQUE, dataset_id BIGINT NOT NULL,
    total_count INT DEFAULT 0, success_count INT DEFAULT 0, failed_count INT DEFAULT 0,
    avg_recall_at_5 DECIMAL(8,6), avg_recall_at_10 DECIMAL(8,6),
    avg_precision_at_5 DECIMAL(8,6), avg_precision_at_10 DECIMAL(8,6),
    avg_mrr DECIMAL(8,6), avg_ndcg_at_5 DECIMAL(8,6), avg_ndcg_at_10 DECIMAL(8,6),
    avg_faithfulness DECIMAL(8,6), avg_answer_correctness DECIMAL(8,6),
    avg_answer_relevance DECIMAL(8,6), avg_hallucination_score DECIMAL(8,6),
    avg_latency_ms DECIMAL(12,3), p90_latency_ms DECIMAL(12,3),
    summary_json CLOB, created_at TIMESTAMP NOT NULL
);
CREATE TABLE eval_compare_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    before_run_id BIGINT NOT NULL, after_run_id BIGINT NOT NULL,
    recall_at_10_delta DECIMAL(8,6), mrr_delta DECIMAL(8,6),
    faithfulness_delta DECIMAL(8,6), answer_correctness_delta DECIMAL(8,6),
    hallucination_score_delta DECIMAL(8,6), conclusion CLOB, created_at TIMESTAMP NOT NULL
);
CREATE TABLE eval_governance_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id VARCHAR(64), project_id VARCHAR(64), snapshot_date DATE NOT NULL,
    total_candidate_count BIGINT DEFAULT 0, approved_candidate_count BIGINT DEFAULT 0,
    rejected_candidate_count BIGINT DEFAULT 0, candidate_approval_rate DECIMAL(8,6),
    knowledge_reuse_rate DECIMAL(8,6), contamination_rate DECIMAL(8,6),
    privacy_leakage_rate DECIMAL(8,6), gap_resolve_rate DECIMAL(8,6),
    created_at TIMESTAMP NOT NULL
);
CREATE TABLE privacy_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(64), knowledge_id BIGINT, tenant_id VARCHAR(64), project_id VARCHAR(64),
    event_type VARCHAR(64) NOT NULL, risk_level VARCHAR(32), description CLOB,
    created_at TIMESTAMP NOT NULL
);
