CREATE TABLE knowledge_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255), claim CLOB, content CLOB NOT NULL, summary CLOB, knowledge_type VARCHAR(64),
    trust_level VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, scope_type VARCHAR(32) NOT NULL,
    user_id VARCHAR(64), conversation_id VARCHAR(64), project_id VARCHAR(64), tenant_id VARCHAR(64),
    source_type VARCHAR(64), source_ref CLOB, evidence CLOB, embedding_id VARCHAR(128),
    embedding_model VARCHAR(128), embedding_dimension INT, confidence DECIMAL(5,4),
    privacy_score DECIMAL(5,4), version INT NOT NULL DEFAULT 1, hash VARCHAR(64) NOT NULL UNIQUE,
    approved_by VARCHAR(64), approved_at TIMESTAMP, reject_reason CLOB,
    created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, expires_at TIMESTAMP,
    promotion_stage VARCHAR(32), promotion_score DECIMAL(5,4), llm_pre_review_result CLOB,
    normalized_claim CLOB, claim_hash VARCHAR(64), llm_score DECIMAL(5,4),
    source_score DECIMAL(5,4), evidence_score DECIMAL(5,4), feedback_score DECIMAL(5,4),
    usage_score DECIMAL(5,4), general_value_score DECIMAL(5,4),
    privacy_risk DECIMAL(5,4) DEFAULT 0, conflict_risk DECIMAL(5,4) DEFAULT 0,
    stale_risk DECIMAL(5,4) DEFAULT 0, applicable_version VARCHAR(128),
    valid_from TIMESTAMP, valid_to TIMESTAMP, source_time TIMESTAMP, last_verified_at TIMESTAMP,
    usage_count INT DEFAULT 0, positive_feedback_count INT DEFAULT 0,
    negative_feedback_count INT DEFAULT 0, tags_json CLOB,
    previous_trust_level VARCHAR(32), previous_status VARCHAR(32)
);
CREATE TABLE rag_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64), conversation_id VARCHAR(64), project_id VARCHAR(64), tenant_id VARCHAR(64),
    question CLOB NOT NULL, rewritten_query CLOB, final_prompt CLOB, answer CLOB,
    max_vector_score DECIMAL(8,6), avg_vector_score DECIMAL(8,6), max_rerank_score DECIMAL(8,6),
    answer_confidence DECIMAL(5,4), possible_gap BOOLEAN NOT NULL, gap_score DECIMAL(5,4),
    gap_types CLOB, gap_reason CLOB, prompt_tokens INT, completion_tokens INT, latency_ms BIGINT,
    status VARCHAR(32), error_message CLOB, created_at TIMESTAMP NOT NULL
);
CREATE TABLE retrieval_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL,
    knowledge_id BIGINT, query CLOB, search_type VARCHAR(32), vector_score DECIMAL(8,6),
    keyword_score DECIMAL(8,6), rerank_score DECIMAL(8,6), trust_score DECIMAL(8,6),
    final_score DECIMAL(8,6), trust_level VARCHAR(32), scope_type VARCHAR(32), rank_no INT,
    used_in_prompt BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, trace_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64), feedback_type VARCHAR(64) NOT NULL, feedback_content CLOB,
    corrected_answer CLOB, processed BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE review_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL, reviewer_id VARCHAR(64), review_action VARCHAR(64),
    review_comment CLOB, created_at TIMESTAMP NOT NULL, reviewed_at TIMESTAMP
);
CREATE TABLE promotion_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL, task_type VARCHAR(32) NOT NULL, retry_count INT DEFAULT 0,
    error_message CLOB, started_at TIMESTAMP, finished_at TIMESTAMP, created_at TIMESTAMP NOT NULL
);
CREATE TABLE conflict_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, candidate_knowledge_id BIGINT NOT NULL,
    existing_knowledge_id BIGINT NOT NULL, conflict_type VARCHAR(32) NOT NULL,
    confidence DECIMAL(5,4) NOT NULL, reason CLOB, created_at TIMESTAMP NOT NULL
);
CREATE TABLE knowledge_lineage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, knowledge_id BIGINT NOT NULL,
    parent_knowledge_id BIGINT, source_trace_id VARCHAR(64), source_feedback_id BIGINT,
    action VARCHAR(128) NOT NULL, operator_type VARCHAR(32) NOT NULL,
    operator_id VARCHAR(64), created_at TIMESTAMP NOT NULL
);
