CREATE TABLE knowledge_item (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255),
    claim TEXT,
    content TEXT NOT NULL,
    summary TEXT,
    knowledge_type VARCHAR(64),
    trust_level VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    scope_type VARCHAR(32) NOT NULL,
    user_id VARCHAR(64),
    conversation_id VARCHAR(64),
    project_id VARCHAR(64),
    tenant_id VARCHAR(64),
    source_type VARCHAR(64),
    source_ref TEXT,
    evidence TEXT,
    embedding_id VARCHAR(128),
    embedding_model VARCHAR(128),
    embedding_dimension INT,
    confidence DECIMAL(5,4),
    privacy_score DECIMAL(5,4),
    version INT NOT NULL DEFAULT 1,
    hash VARCHAR(64) NOT NULL UNIQUE,
    approved_by VARCHAR(64),
    approved_at DATETIME(6),
    reject_reason TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    expires_at DATETIME(6),
    INDEX idx_knowledge_retrieval(status, trust_level, scope_type),
    INDEX idx_knowledge_scope_owner(tenant_id, project_id, user_id, conversation_id)
);

CREATE TABLE rag_trace (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_id VARCHAR(64) NOT NULL UNIQUE,
    user_id VARCHAR(64),
    conversation_id VARCHAR(64),
    project_id VARCHAR(64),
    tenant_id VARCHAR(64),
    question TEXT NOT NULL,
    rewritten_query TEXT,
    final_prompt TEXT,
    answer TEXT,
    max_vector_score DECIMAL(8,6),
    avg_vector_score DECIMAL(8,6),
    max_rerank_score DECIMAL(8,6),
    answer_confidence DECIMAL(5,4),
    possible_gap BOOLEAN NOT NULL DEFAULT FALSE,
    gap_score DECIMAL(5,4),
    gap_types TEXT,
    gap_reason TEXT,
    prompt_tokens INT,
    completion_tokens INT,
    latency_ms BIGINT,
    status VARCHAR(32),
    error_message TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE retrieval_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_id VARCHAR(64) NOT NULL,
    knowledge_id BIGINT,
    query TEXT,
    search_type VARCHAR(32),
    vector_score DECIMAL(8,6),
    keyword_score DECIMAL(8,6),
    rerank_score DECIMAL(8,6),
    trust_score DECIMAL(8,6),
    final_score DECIMAL(8,6),
    trust_level VARCHAR(32),
    scope_type VARCHAR(32),
    rank_no INT,
    used_in_prompt BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_retrieval_trace(trace_id, rank_no),
    CONSTRAINT fk_retrieval_trace FOREIGN KEY (trace_id) REFERENCES rag_trace(trace_id)
);

CREATE TABLE feedback (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    trace_id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64),
    feedback_type VARCHAR(64) NOT NULL,
    feedback_content TEXT,
    corrected_answer TEXT,
    processed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT fk_feedback_trace FOREIGN KEY (trace_id) REFERENCES rag_trace(trace_id)
);

CREATE TABLE review_task (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    knowledge_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    reviewer_id VARCHAR(64),
    review_action VARCHAR(64),
    review_comment TEXT,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_at DATETIME(6),
    INDEX idx_review_pending(status, created_at),
    CONSTRAINT fk_review_knowledge FOREIGN KEY (knowledge_id) REFERENCES knowledge_item(id)
);
